### ISSUE TITLE
Подчеркивание в переменных означает, что это DOM-элементы?

### ISSUE THREAD

**Issue by rogallic** [kapralnsk/joy_of_painting#2]
```javascript
var palette = $('#palette');
var brush_picker = $('#brush');
var canvas_elt = $('#canvas');
var canvas = canvas_elt[0];
var context = canvas.getContext("2d");
var brush = 8;
context.lineCap="round";
context.lineWidth = brush;
var color = "#000000";
var currentPoint={x:0, y:0}, previousPoint={x:0, y:0}
var mousePressed = false;
```
Жаль, что нет постоянства в кодстайле javascript-а. В некоторых компаниях этому уделяют много внимания. Потребуется соблюдение стиля как в python. Но мне нравится, что в коде выделены самые необходимые функции без большого количества оберток и велосипедов. Интересно, snake_case означает что это DOM-элементы? Или просто переход между python-ом и js-ом так повлиял.

**Comment by kapralnsk** [comment]
идея выделить таким образом DOM элементы интересная, но тут исключительно прыжки между python и js так повлияли.
вообще в js коде намеревался использовать camelCase - насколько я знаю, именно он чаще используется там
